### ISSUE TITLE
Ahamo mbn file

### ISSUE THREAD

**Issue by lameventanas** [AndroPlus-org/magisk-module-oneplus-mbn#2]
I'm trying to enable VoLTE on a Oneplus 5t with Ahamo by using efstools.
Which MBN file should I use?

**Comment by AndroPlus-org** [comment]
Please use DCM (=docomo) mbn.
https://github.com/AndroPlus-org/magisk-module-oneplus-mbn/blob/master/mbn/vendor/firmware_mnt/image/modem_pr/mcfg/configs/mcfg_sw/generic/APAC/DCM/pixel_Commercial/mcfg_sw.mbn

**Comment by lameventanas** [comment]
I used the file you linked with efstools (97,500 bytes, md5: dfb55c5b42db97228c1d23ccd88790b0).
I can use data, but phone calls and sms don't work.
How can I fix it?
Thanks.
